const $=s=>document.querySelector(s); const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const r=await fetch((window.EMMY_API_URL || ((location.hostname==='localhost'||location.hostname==='127.0.0.1')&&location.port!=='3000'?'http://localhost:3000':''))+url,{credentials:'include',headers:{'Content-Type':'application/json'},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
let classes=[];
async function load(){try{const c=await api('/api/teacher/classes');classes=c.classes; renderClasses(); fillSelects(); const [rep,ass]=await Promise.all([api('/api/teacher/reports'),api('/api/teacher/assignments')]);$('#reports').innerHTML=rep.reports.length?`<table class="data-table"><tr><th>Class</th><th>Students</th><th>Average</th><th>Passed</th></tr>${rep.reports.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.students}</td><td>${x.average_score}%</td><td>${x.passed_attempts}</td></tr>`).join('')}</table>`:'No classes yet.';$('#assignments').innerHTML=ass.assignments.length?ass.assignments.map(x=>`<div class="list-row"><b>${esc(x.title)}</b><span>${esc(x.class_name)} · ${esc(x.lesson_id)}${x.due_date?' · due '+esc(x.due_date):''}</span></div>`).join(''):'No assignments yet.';}catch(e){$('#msg').textContent=e.message}}
function renderClasses(){$('#classes').innerHTML=classes.length?classes.map(c=>`<div class="list-row"><b>${esc(c.name)}</b><span>${esc(c.class_code)} · ${c.student_count} students</span></div>`).join(''):'<p>No classes yet.</p>'}
function fillSelects(){const html=classes.map(c=>`<option value="${c.id}">${esc(c.name)} (${esc(c.class_code)})</option>`).join('');$('#classSelect').innerHTML=html;$('#assignClass').innerHTML=html}
$('#classForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/teacher/classes',{method:'POST',body:JSON.stringify({name:$('#className').value})});$('#className').value='';await load()}catch(x){$('#msg').textContent=x.message}});
$('#addStudent').onclick=async()=>{try{await api('/api/teacher/classes/'+$('#classSelect').value+'/students',{method:'POST',body:JSON.stringify({username:$('#studentUsername').value})});$('#studentMsg').textContent='Student added.';$('#studentUsername').value='';await load()}catch(x){$('#studentMsg').textContent=x.message}};
$('#assignForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/teacher/assignments',{method:'POST',body:JSON.stringify({classId:$('#assignClass').value,title:$('#assignTitle').value,lessonId:$('#lessonId').value,dueDate:$('#dueDate').value||null})});e.target.reset();await load()}catch(x){$('#msg').textContent=x.message}});load();
