USE emmy_j_code;
ALTER TABLE users MODIFY account_type ENUM('student','teacher','admin') NOT NULL;
CREATE TABLE IF NOT EXISTS classes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 teacher_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(150) NOT NULL,
 class_code VARCHAR(20) NOT NULL UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX idx_classes_teacher (teacher_id)
);
CREATE TABLE IF NOT EXISTS class_members (
 class_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(class_id,user_id),
 FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS assignments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 class_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(180) NOT NULL,
 lesson_id VARCHAR(120) NOT NULL,
 due_date DATE NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(class_id) REFERENCES classes(id) ON DELETE CASCADE,
 INDEX idx_assignments_class(class_id)
);
